### PR TITLE
Add SelectStar method

### PR DESCRIPTION
**Pull request by dshahin**
This is a method for generating a soql query based on an object name.  Optionally show standard fields only.

@jholmes612 @mpond76 @jholmes612 please review

### CODE REVIEW

**Comment by jholmes612** [comment]
Good idea. Will likely have an issue in orgs on different Salesforce versions (between releases) with the assert in the unit test.

**Comment by dshahin** [comment]
I thought that might be an issue.  Is there a better object to use?

**Comment by jholmes612** [comment]
No, all objects could have that issue. Need to assert something else.

**Comment by dshahin** [comment]
Ok, I will just assert result is not null, I guess

**Pull request merged**
