### PR TITLE
add dayOfWeek(Date) method and add auto-install button

### PR DESCRIPTION
**Pull request by dshahin**
added a method for obtaining day of week as a string.

### CODE REVIEW

**Comment by dshahin** [comment]
@jholmes612   can you review this and merge if acceptable?

**Comment by dshahin** [comment]
also added autodeploy button to README

**Comment by jholmes612** [comment]
Looks good. I'd change the test name to "testDayOfWeek()" to be consistent with others.

**Comment by dshahin** [comment]
sounds good, thanks!

**Comment by dshahin** [comment]
I will change it now

**Comment by dshahin** [comment]
@jholmes612 fixed the test name

**Pull request merged**
